# Generated by Django 2.2.10 on 2020-10-16 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_commentt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentt',
            new_name='Comment',
        ),
    ]
